version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=dboperator
      - POSTGRES_PASSWORD=operatorpass123
      - POSTGRES_DB=dboperator
    networks:
      - bridge
    ports:
      - "5245:5432"
    volumes:
      - postgres_data_container:/data/postgres

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - bridge
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/mongodbdb

volumes:
  postgres_data_container:
  mongodb_data_container:

networks:
  bridge:
    # Use a custom driver
    #    driver: custom-driver-1
